spring:
  datasource:
    url: jdbc:postgresql://localhost:50758/mydatabase
    username: myuser
    password: secret

# Hibernate ddl auto ( create, create-drop, validate, update )
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
        ddl-auto: update

# App Properties
demo:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
