spring:
  datasource:
    url: jdbc:postgresql://localhost:53525/mydatabase
    username: myuser
    password: secret

# Hibernate ddl auto ( create, create-drop, validate, update )
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
        ddl-auto: update

# App Properties
demo:
  app:
    jwtSecret: ============================================BezKoder=Spring=================================================
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
    # Swagger
#  openapi:
#    dev-url: http://localhost:8080
#    prod-url: https://demo.com/doc
